name: StockTwits
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic to write data to
    defaultValue: messages
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
